# Generated by Django 5.2.1 on 2025-05-24 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vpn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vpn_instance', models.CharField(max_length=100)),
                ('route_disting', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('svlan', models.PositiveIntegerField(blank=True, null=True)),
                ('cvlan', models.PositiveIntegerField(blank=True, null=True)),
                ('qos_profile', models.CharField(blank=True, null=True)),
                ('traffic_policy', models.CharField(blank=True, null=True)),
                ('subnet_mask', models.CharField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=15, null=True)),
                ('id_vpn_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interfacesapp.vpn')),
            ],
        ),
    ]
