# Generated by Django 5.2.1 on 2025-05-24 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfacesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rutas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lan', models.CharField(max_length=15)),
                ('lan_mask', models.CharField(max_length=15)),
                ('wan', models.CharField(max_length=15, unique=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('vpn_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interfacesapp.vpn')),
            ],
        ),
    ]
