# Generated by Django 5.2.1 on 2025-05-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfacesapp', '0002_rutas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutas',
            name='wan',
            field=models.CharField(max_length=15),
        ),
    ]
